name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: main
      shell: cmd
      run: |
        python -m pip install mugicli
        pyfind -maxdepth 1 C:\ > pyfind1.txt
        pyfind -maxdepth 1 "C:\Program Files" > pyfind2.txt
        pyfind -maxdepth 1 "C:\Program Files (x86)" > pyfind3.txt
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: pyfind
        path: pyfind*.txt
