name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: main
      shell: cmd
      run: |
        python -m pip install mugicli
        pyfind -maxdepth 1 C:\
        pyfind -maxdepth 1 "C:\Program Files"
        pyfind -maxdepth 1 "C:\Program Files (x86)"
        C:\msys64\usr\bin\bash -lc "ls -la ~/.ssh"
